'use strict';

const ACCESSORY_SECTION = 'section';
const ACCESSORY_SWITCH = "switch";
const ACCESSORY_OUTLET = 'outlet';

const JABLOTRON_SECTION = 'section';
const JABLOTRON_PGM = 'pgm';

const DEFAULT_POLL_INTERVAL = 60;

module.exports = { ACCESSORY_SECTION, ACCESSORY_SWITCH, ACCESSORY_OUTLET, JABLOTRON_SECTION, JABLOTRON_PGM, DEFAULT_POLL_INTERVAL };